### ISSUE TITLE
Metadata still links to https://github.com/Coernel82/SEPA-QR-for-Woocommerce

### ISSUE THREAD

**Issue by Florian1990** [petermorlion/SEPA-QR-for-Woocommerce#3]
Hi,

I just installed this plugin. However it still tells, it was the version by Coernel82.

![grafik](https://github.com/petermorlion/SEPA-QR-for-Woocommerce/assets/7100594/072a6706-2870-4078-a164-a62335e60c9d)

Looking at the code I am not sure where the info is from. Perhaps it is from the comments in https://github.com/petermorlion/SEPA-QR-for-Woocommerce/blob/main/mxp-sepaqr/muxp-sepaqr.php .

Cheers!

**Comment by petermorlion** [comment]
Thanks for noticing this. I fixed it in the latest version.
