### ISSUE TITLE
The QR code uses the wrong order number in case a "custom order number" plugin is used

### ISSUE THREAD

**Issue by developer58456** [petermorlion/SEPA-QR-for-Woocommerce#4]
Can be fixed by using the function call `muxp_get_qrcode($order->get_total(), $order->get_order_number())` in `muxp_add_text_to_thankyoupage` and `muxp_email_after_order_table`.

**Comment by petermorlion** [comment]
Hi @developer58456 , thanks for the suggestion. Fixed in the latest commit.
